---
- name: Manually install Homebrew via git
  hosts: localhost
  #hosts: all
  connection: local
    #become: yes
    #become_user: "{{ ansible_user_id }}"
  # yes might fail in a minimal docker env
  gather_facts: yes
  vars:
    homebrew_user: "{{ ansible_user_id }}" # #"{{ ansible_user_id }}" #homebrew_user: "{{ lookup('env', 'USER') }}"
    homebrew_git_repo: https://github.com/Homebrew/brew
    homebrew_release: master  # or a tag like 4.2.0
    brew_formulae: 
      - neovim
      - asdf
      - ca-certificates
      - colima
      - delve
      - docker
      - docker-completion
      - gettext
      - git
      - git-filter-repo
      - htop
      - lazydocker
      - lazygit
      - libevent
      - libunistring
      - libuv
      - lima
      - lpeg
      - luajit
      - luv
      - mpdecimal
      - ncurses
      - nvm
      - openssl@3
      - pcre2
      - python@3.13
      - readline
      - ripgrep
      - sqlite
      - starship
      - stow
      - tmux
      - tree-sitter
      - unibilium
      - utf8proc
      - xz
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-vi-mode


  tasks:

    - name: Ensure /home/linuxbrew/.linuxbrew exists
      become: yes
      file:
        path: "/home/linuxbrew/.linuxbrew"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'

    - name: Clone Homebrew GitHub repo
      ansible.builtin.git:
        repo: "{{ homebrew_git_repo }}"
        dest: "/home/linuxbrew/.linuxbrew/Homebrew"
        version: "{{ homebrew_release }}"
      become_user: "{{ homebrew_user }}"

    - name: Create bin directory for brew
      ansible.builtin.file:
        path: "/home/linuxbrew/.linuxbrew/bin"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"

    - name: Create a symbolic link for brew
      ansible.builtin.file:
        src: "/home/linuxbrew/.linuxbrew/Homebrew/bin/brew"
        dest: "/home/linuxbrew/.linuxbrew/bin/brew"
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        state: link

    - name: Add brew to .zshrc
      become: false
      lineinfile:
        path: "/home/{{ homebrew_user }}/.zshrc"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        insertafter: EOF

    - name: Install Formula
      community.general.homebrew:
        name: "{{ brew_formulae }}"
        state: present
        path: "/home/linuxbrew/.linuxbrew/bin"
      become_user: "{{ homebrew_user }}"
      become: yes

    - name: Ensure ~/dotfiles directory exists
      become: yes
      file:
        path: "/home/{{ homebrew_user }}/dotfiles/config/"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'

    - name: Copy dotfiles packages to user's home
      copy:
        src: "./{{ item }}"
        dest: "/home/{{ homebrew_user }}/dotfiles/config"
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: preserve
      loop:
        - alacritty
        - htop  
        - nvim
        # - git
        # - vim
        # - tmux

    - name: Ensure ~/.config directory exists
      become: yes
      file:
        path: "/home/{{ homebrew_user }}/.config/"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'

    - name: Run stow with Homebrew path
      shell: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        cd ~/dotfiles
        stow config --target /home/{{ homebrew_user }}/.config --verbose=2
      args:
        executable: /bin/zsh  # optional: in case your system prefers zsh

    # - name: Run stow
    #   shell: "stow ~/dotfiles --target {{ ansible_env.HOME }} --verbose=2"
    #   register: result
    #   changed_when: 'result.stderr is search("LINK: ")'

    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

