---
- name: Manually install Homebrew via git
  hosts: localhost
  #hosts: all
  connection: local
    #become: yes
    #become_user: "{{ ansible_user_id }}"
  # yes might fail in a minimal docker env
  gather_facts: yes
  vars:
    homebrew_user: "{{ ansible_user_id }}" # #"{{ ansible_user_id }}" #homebrew_user: "{{ lookup('env', 'USER') }}"
    homebrew_git_repo: https://github.com/Homebrew/brew
    homebrew_release: master  # or a tag like 4.2.0
    brew_formulae: 
      - neovim
      - asdf
      - ca-certificates
      - colima
      - delve
      - docker
      - docker-completion
      - gettext
      - git
      - git-filter-repo
      - htop
      - lazydocker
      - lazygit
      - libevent
      - libunistring
      - libuv
      - lima
      - lpeg
      - luajit
      - luv
      - mpdecimal
      - ncurses
      - nvm
      - openssl@3
      - pcre2
      - python@3.13
      - readline
      - ripgrep
      - sqlite
      - starship
      - stow
      - tmux
      - tree-sitter
      - unibilium
      - utf8proc
      - xz
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-vi-mode


  tasks:

    - name: Ensure /home/linuxbrew/.linuxbrew exists
      become: yes
      file:
        path: "/home/linuxbrew/.linuxbrew"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'
      tags:
      - brew

    - name: Clone Homebrew GitHub repo
      ansible.builtin.git:
        repo: "{{ homebrew_git_repo }}"
        dest: "/home/linuxbrew/.linuxbrew/Homebrew"
        version: "{{ homebrew_release }}"
      become_user: "{{ homebrew_user }}"
      tags:
      - brew

    - name: Create bin directory for brew
      ansible.builtin.file:
        path: "/home/linuxbrew/.linuxbrew/bin"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
      tags:
      - brew

    - name: Create a symbolic link for brew
      ansible.builtin.file:
        src: "/home/linuxbrew/.linuxbrew/Homebrew/bin/brew"
        dest: "/home/linuxbrew/.linuxbrew/bin/brew"
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        state: link
      tags:
      - brew

    - name: Add brew to .bashrc
      become: false
      lineinfile:
        path: "/home/{{ homebrew_user }}/.bashrc"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        insertafter: EOF
      tags:
      - brew

    - name: Install Formula
      community.general.homebrew:
        name: "{{ brew_formulae }}"
        state: present
        path: "/home/linuxbrew/.linuxbrew/bin"
      become_user: "{{ homebrew_user }}"
      become: yes
      tags:
      - brew-install

    - name: Ensure ~/dotfiles directory exists
      become: yes
      file:
        path: "/home/{{ homebrew_user }}/dotfiles/config/"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'
      tags:
      - dotfiles-config

    - name: Copy config dotfiles packages to user's home
      copy:
        src: "./config/.config/{{ item }}"
        dest: "/home/{{ homebrew_user }}/dotfiles/config"
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: preserve
      loop:
        - alacritty
        - nvim
        # - git
        # - vim
        # - tmux
      tags:
      - dotfiles-config

    - name: Ensure ~/.config directory exists
      become: yes
      file:
        path: "/home/{{ homebrew_user }}/.config/"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: '0755'
      tags:
      - dotfiles

    - name: Install missing Homebrew formulae
      shell: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install {{ item }}
      args:
        executable: /usr/bin/zsh
      loop:
        # - colima
        # - stow
        - delve
        - docker
        - docker-completion
        - git-filter-repo
        - htop
        - lazydocker
        - lazygit
        - libevent
        - lima
        - luv
        - mpdecimal
        - ripgrep
        - tmux
        - zsh-autocomplete
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-vi-mode
      tags: install_missing_formulae

    - name: Run stow with Homebrew path
      # export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      shell: |
        cd ~/dotfiles
        stow config --target /home/{{ homebrew_user }}/.config --verbose=2
      args:
        executable: /usr/bin/bash  # optional: in case your system prefers zsh
      tags:
      - stow

    # TODO: missing docs to put in the repo:
    # /home/urbpi/.zsh_plugins:source:1: no such file or directory: /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    # /home/urbpi/.zsh_plugins:source:2: no such file or directory: /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    # /home/urbpi/.zsh_plugins:source:3: no such file or directory: /opt/homebrew/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
    # /home/urbpi/.zsh_plugins:source:4: no such file or directory: /opt/homebrew/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
    # /home/urbpi/.zshrc:153: command not found: tmuxifier
    # /home/urbpi/.zshrc:159: command not found: starship have to install the preset too
    - name: Copy config dotfiles packages to user's home
      copy:
        src: "./{{ item }}"
        dest: "/home/{{ homebrew_user }}/dotfiles"
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_user }}"
        mode: preserve
      loop:
        - git
        - tmux
        - vim
        - zsh
      tags:
      - stow

    - name: Run stow with Homebrew path
      shell: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        cd ~/dotfiles
        stow git tmux vim zsh --target /home/{{ homebrew_user }} --verbose=2
      args:
        executable: /usr/bin/bash  # optional: in case your system prefers zsh
      tags:
      - stow

    # TODO: have to git init and set remote for dotfiles
    # TODO: had to manually install swith to zsh. 
    # TODO: had to manually install stow. Error was that stow was not existing
    # TODO: had to manually install starship. Error was that stow was not existing
    # TODO: had to manually install tmuxifier. Error was that stow was not existing
    # TODO: have to manually install Nerd Fonts.

    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1
      tags:
      - ohmyzsh

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags:
      - zsh

    - name: Install ZSH
      become: true
      ansible.builtin.package:
        name: zsh
        state: present
      tags:
      - zsh

    - name: Run zsh
      shell: |
        zsh
      args: /usr/bin/zsh
      tags:
       - switch-zsh

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      tags:
      - switch-zsh
